apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    aegis.flow/project: {{ .Values.projectRef | quote }}
    aegis.flow/egress-namespace: "true"
