apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aegis-egress-proxy.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "aegis-egress-proxy.labels" . | nindent 4 }}
automountServiceAccountToken: false
