{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegis-egress-proxy.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "aegis-egress-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aegis-egress-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin-metrics
      path: /stats/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
